const myBooks= {
  // Title, Author, My Rating, Year Published, Genre(s)
  haveRead: [
    ["Harry Potter and the Deathly Hallows", "J. K. Rowling", 5, 2007, "Fantasy"],
    ["Harry Potter and the Prisoner of Azkaban", "J. K. Rowling", 5, 1999, "Fantasy"],
    ["Harry Potter and the Half-Blood Prince", "J. K. Rowling", 5, 2005, "Fantasy"],
    ["Harry Potter and the Goblet of Fire", "J. K. Rowling", 5, 2000, "Fantasy"],
    ["The Return of the King", "J. R. R. Tolkien", 5, 1955, "Fantasy"],
    ["The Wise Man's Fear", "Patrick Rothfuss", 4, 2011, "Fantasy"],
    ["A Storm of Swords", "George R. R. Martin", 5, 2000, "Fantasy"],
    ["The Hero of Ages", "Brandon Sanderson", 3, 2008, "Fantasy"],
    ["The Name of the Wind", "Patrick Rothfuss", 4, 2007, "Fantasy"],
    ["Project Hail Mary", "Andy Weir", 4, 2021, "Science Fiction"],
    ["Harry Potter and the Order of the Phoenix", "J. K. Rowling", 5, 2003, "Fantasy"],
    ["The Winter of the Witch", "Katherine Arden", 5, 2019, "Fantasy"],
    ["Morning Star", "Pierce Brown", 4, 2016, "Science Fiction"],
    ["The Two Towers", "J. R. R. Tolkien", 5, 1954, "Fantasy"],
    ["The Final Empire", "Brandon Sanderson", 3, 2006, "Fantasy"],
    ["Harry Potter and the Sorcerer's Stone", "J. K. Rowling", 5, 1997, "Fantasy"],
    ["The Missing of Clairdelune", "Christelle Dabos", 4, 2015, "Fantasy"],
    ["Golden Son", "Pierce Brown", 4, 2015, "Science Fiction"],
    ["A Game of Thrones", "George R. R. Martin", 5, 1996, "Fantasy"],
    ["Harry Potter and the Chamber of Secrets", "J. K. Rowling", 5, 1998, "Fantasy"],
    ["The House in the Cerulean Sea", "T. J. Klune", 4, 2020, "Fantasy"],
    ["The Dark Forest", "Cixin Liu", 2, 2008, "Science Fiction"],
    ["A Clash of Kings", "George R. R. Martin", 5, 1998, "Fantasy"],
    ["The Martian", "Andy Weir", 5, 2011, "Science Fiction"],
    ["The Fellowship of the Ring", "J. R. R. Tolkien", 5, 1954, "Fantasy"],
    ["The Well of Ascension", "Brandon Sanderson", 3, 2007, "Fantasy"],
    ["The Girl in the Tower", "Katherine Arden", 5, 2017, "Fantasy"],
    ["The Stone Sky", "N. K. Jemisin", 2, 2017, "Fantasy"],
    ["A Dance with Dragons", "George R. R. Martin", 4, 2011, "Fantasy"],
    ["The Hunger Games", "Suzanne Collins", 5, 2008, "Dystopia"],
    ["A Conjuring of Light", "V. E. Schwab", 4, 2017, "Fantasy"],
    ["All the Light We Cannot See", "Anthony Doerr", 4, 2014, "Historical Fiction"],
    ["Catching Fire", "Suzanne Collins", 4, 2009, "Dystopia"],
    ["Ender's Shadow", "Orson Scott Card", 5, 1999, "Science Fiction"],
    ["The Fifth Season", "N. K. Jemisin", 2, 2015, "Fantasy"],
    ["The Obelisk Gate", "N. K. Jemisin", 3, 2016, "Fantasy"],
    ["Pride and Prejudice", "Jane Austen", 5, 1813, "Classics"],
    ["The Last Graduate", "Naomi Novik", 5, 2021, "Fantasy"],
    ["And Then There Were None", "Agatha Christie", 3, 1939, "Mystery"],
    ["Exhalation", "Ted Chiang", 3, 2019, "Science Fiction"],
    ["Summer Knight", "Jim Butcher", 3, 2002, "Fantasy"],
    ["Red Rising", "Pierce Brown", 4, 2014, "Science Fiction"],
    ["Dune", "Frank Herbert", 1, 1965, "Science Fiction"],
    ["Outlander", "Diana Gabaldon", 2, 1991, "Fantasy"],
    ["Stories of Your Life and Others", "Ted Chiang", 2, 2002, "Science Fiction"],
    ["Circe", "Madeline Miller", 2, 2018, "Fantasy"],
    ["Ready Player One", "Ernest Cline", 5, 2011, "Science Fiction"],
    ["The Memory of Babel", "Christelle Dabos", 4, 2017, "Fantasy"],
    ["A Gathering of Shadows", "V. E. Schwab", 4, 2016, "Fantasy"],
    ["The Hitchhiker's Guide to the Galaxy", "Douglas Adams", 1, 1979, "Science Fiction"],
    ["The Priory of the Orange Tree", "Samantha Shannon", 4, 2019, "Fantasy"],
    ["Spinning Silver", "Naomi Novik", 5, 2018, "Fantasy"],
    ["The Invisible Life of Addie LaRue", "V. E. Schwab", 4, 2020, "Science Fiction"],
    ["The Silent Patient", "Alex Michaelides", 3, 2019, "Thriller"],
    ["Foundation", "Isaac Asimov", 1, 1951, "Science Fiction"],
    ["Under the Whispering Door", "T. J. Klune", 3, 2021, "Fantasy"],
    ["Recursion", "Blake Crouch", 4, 2019, "Science Fiction"],
    ["The Girl with the Dragon Tattoo", "Stieg Larson", 2, 2005, "Thriller"],
    ["The Golden Enclaves", "Naomi Novik", 5, 2022, "Fantasy"],
    ["A Feast for Crows", "George R. R. Martin", 4, 2005, "Fantasy"],
    ["League of Dragons", "Naomi Novik", 4, 2016, "Fantasy"],
    ["Divergent", "Veronica Roth", 4, 2011, "Dystopia"],
    ["The Subtle Knife", "Philip Pullman", 5, 1997, "Fantasy"],
    ["Jane Eyre", "Charlotte Bronte", 1, 1847, "Classics"],
    ["Grave Peril", "Jim Butcher", 3, 2001, "Fantasy"],
    ["The Last Wish", "Andrzej Sapkowski", 3, 1993, "Fantasy"],
    ["Dark Matter", "Blake Crouch", 4, 2016, "Science Fiction"],
    ["The Handmaid's Tale", "Margaret Atwood", 1, 1985, "Classics"],
    ["Jade City", "Fonda Lee", 3, 2017, "Fantasy"],
    ["The Bear and the Nightingale", "Katherine Arden", 5, 2017, "Fantasy"],
    ["The Amber Spyglass", "Philip Pullman", 2, 2000, "Fantasy"],
    ["The Invasion of the Tearling", "Erika Johnansen", 3, 2015, "Fantasy"],
    ["The Three Body Problem", "Cixin Liu", 2, 2008, "Science Fiction"],
    ["The Other Boleyn Girl", "Philippa Gregory", 4, 2001, "Historical Fiction"],
    ["Mockingjay", "Suzanna Collins", 3, 2010, "Dystopia"],
    ["The Goblin Emperor", "Katherine Addison", 2, 2014, "Fantasy"],
    ["Victory of Eagles", "Naomi Novik", 4, 2008, "Fantasy"],
    ["A Darker Shade of Magic", "V.E. Schwab", 4, 2015, "Fantasy"],
    ["His Majesty's Dragon", "Naomi Novik", 4, 2006, "Fantasy"],
    ["The Once and Future Witches", "Alix E. Harrow", 4, 2020, "Fantasy"],
    ["A Winter's Promise", "Christelle Dabos", 4, 2013, "Fantasy"],
    ["Uprooted", "Naomi Novik", 4, 2015, "Fantasy"],
    ["Ninth House", "Leigh Bardugo", 2, 2019, "Fantasy"],
    ["The Ten Thousand Doors of January", "Alix E. Harrow", 4, 2019, "Fantasy"],
    ["The Golden Compass", "Philip Pullman", 4, 1995, "Fantasy"],
    ["A Wizard of Earthsea", "Ursula K. Le Guin", 1, 1968, "Fantasy"],
    ["Waking Gods", "Sylvain Neuvel", 2, 2017, "Science Fiction"],
    ["Shadow of the Giant", "Orson Scott Card", 5, 2005, "Science Fiction"],
    ["The Mysterious Affair at Styles", "Agatha Christie", 3, 1920, "Mystery"],
    ["The Time Traveler's Wife", "Audrey Niffenegger", 1, 2003, "Science Fiction"],
    ["A Deadly Education", "Naomi Novik", 5, 2020, "Fantasy"],
    ["The Queen of the Tearling", "Erika Johansen", 4, 2014, "Fantasy"],
    ["Fool Moon", "Jim Butcher", 2, 2001, "Fantasy"],
    ["Brave New World", "Aldous Huxley", 1, 1932, "Classics"],
    ["Blood of Tyrants", "Naomi Novik", 3, 2013, "Fantasy"],
    ["Ancillary Justice", "Ann Leckie", 1, 2013, "Science Fiction"],
    ["Insurgent", "Veronica Roth", 3, 2012, "Dystopia"],
    ["Storm Front", "Jim Butcher", 3, 2000, "Fantasy"],
    ["Empire of Ivory", "Naomi Novik", 3, 2007, "Fantasy"],
    ["Crucible of Gold", "Naomi Novik", 3, 2012, "Fantasy"],
    ["Shadow of the Hegemon", "Orson Scott Card", 5, 2000, "Science Fiction"],
    ["The Girl on the Train", "Paula Hawkins", 3, 2015, "Thriller"],
    ["Magpie Murders", "Anthony Horowitz", 3, 2016, "Mystery"],
    ["The White Queen", "Philippa Gregory", 4, 2009, "Historical Fiction"],
    ["Titan", "John Varley", 2, 1979, "Science Fiction"],
    ["Angels and Demons", "Dan Brown", 4, 2000, "Thriller"],
    ["The Da Vinci Code", "Dan Brown", 4, 2003, "Thriller"],
    ["Tell No Lies", "Gregg Andrew Hurwitz", 3, 2013, "Thriller"],
    ["The Boleyn Inheritance", "Philippa Gregory", 4, 2006, "Historical Fiction"],
    ["Black Powder War", "Naomi Novik", 3, 2006, "Fantasy"],
    ["Shadow Puppets", "Orson Scott Card", 4, 2002, "Science Fiction"],
    ["Throne of Jade", "Naomi Novik", 2, 2006, "Fantasy"],
    ["Wuthering Heights", "Emily Bronte", 3, 1847, "Classics"],
    ["The Stranger Diaries", "Elly Griffiths", 3, 2018, "Mystery"],
    ["Inferno", "Dan Brown", 3, 2013, "Thriller"],
    ["The Murder on the Links", "Agatha Christie", 3, 1923, "Mystery"],
    ["The Ballad of Songbirds and Snakes", "Suzanne Collins", 4, 2020, "Dystopia"],
    ["Never Let Me Go", "Kazuo Ishiguro", 1, 2005, "Science Fiction"],
    ["Northanger Abbey", "Jane Austen", 2, 1817, "Classics"],
    ["The Strange Case of Dr. Jekyll and Mr. Hyde", "Robert Louis Stevenson", 2, 1886, "Classics"],
    ["Sleeping Giants", "Sylvain Neuvel", 3, 2016, "Science Fiction"],
    ["The Rule of Mirrors", "Caragh M. O'Brien", 3, 2016, "Science Fiction"],
    ["The Red Queen", "Philippa Gregory", 4, 2010, "Historical Fiction"],
    ["The Duke and I", "Julia Quinn", 3, 2000, "Historical Fiction"],
    ["Annihilation", "Jeff VanderMeer", 2, 2014, "Science Fiction"],
    ["Tongues of Serpents", "Naomi Novik", 3, 2010, "Fantasy"],
    ["The Storm of Echoes", "Christelle Dabos", 4, 2019, "Fantasy"],
    ["Deception Point", "Dan Brown", 3, 2001, "Thriller"],
    ["The Fate of the Tearling", "Erika Johansen", 2, 2016, "Fantasy"],
    ["The Lost Symbol", "Dan Brown", 3, 2009, "Thriller"],
    ["The Woman in Cabin 10", "Ruth Ware", 5, 2016, "Thriller"],
    ["Breaking Dawn", "Stephanie Meyer", 3, 2008, "Fantasy"],
    ["Eclipse", "Stephanie Meyer", 3, 2007, "Fantasy"],
    ["Lord of the Flies", "William Golding", 1, 1954, "Classics"],
    ["Digital Fortress", "Dan Brown", 2, 1998, "Thriller"],
    ["Juniper and Thorn", "Ava Reid", 4, 2022, "Fantasy"],
    ["The Keep of Ages", "Caragh M. O'Brien", 2, 2017, "Science Fiction"],
    ["Twilight", "Stephanie Meyer", 4, 2005, "Fantasy"],
    ["The Vault of Dreamers", "Caragh M. O'Brien", 3, 2014, "Science Fiction"],
    ["Allegiant", "Veronica Roth", 2, 2013, "Dystopia"],
    ["The Memory of Earth", "Orson Scott Card", 1, 1992, "Science Fiction"],
    ["New Moon", "Stephanie Meyer", 3, 2006, "Fantasy"],
    ["The Wolf and The Woodsman", "Ava Reid", 4, 2021, "Fantasy"],
    ["Arcanum", "Simon Morden", 3, 2013, "Fantasy"],
    ["The Wise Woman", "Philippa Gregory", 3, 1992, "Historical Fiction"]

  ],
};
